# Generated by Django 4.0.5 on 2022-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ek', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('sex', models.CharField(max_length=250)),
                ('age', models.IntegerField(max_length=1)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('team', models.CharField(max_length=250)),
                ('noc', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=250)),
                ('sport', models.CharField(max_length=250)),
                ('event', models.CharField(max_length=250)),
                ('medal', models.CharField(max_length=6)),
            ],
        ),
    ]
