# Generated by Django 4.0.5 on 2022-06-05 16:06

from django.db import migrations, models
import olympics.models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0002_rename_ek_event_event_key_alter_event_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.IntegerField(validators=[olympics.models.isPositive]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_key',
            field=models.IntegerField(validators=[olympics.models.isPositive]),
        ),
        migrations.AlterField(
            model_name='event',
            name='height',
            field=models.IntegerField(validators=[olympics.models.isPositive]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sex',
            field=models.CharField(max_length=1, validators=[olympics.models.validate_sex]),
        ),
        migrations.AlterField(
            model_name='event',
            name='weight',
            field=models.IntegerField(validators=[olympics.models.isPositive]),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(validators=[olympics.models.validate_year]),
        ),
    ]
