# Generated by Django 4.0.5 on 2022-06-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0003_alter_event_age_alter_event_event_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_key',
            new_name='Athlete_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='games',
            new_name='Games',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='height',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='medal',
            new_name='Medal',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='noc',
            new_name='NOC',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='season',
            new_name='Season',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sex',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sport',
            new_name='Sport',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='team',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='weight',
            new_name='Weight',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='year',
            new_name='Year',
        ),
    ]
