# Generated by Django 4.0.5 on 2022-06-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0004_rename_age_event_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Athlete_id',
            new_name='event_key',
        ),
    ]
