# Generated by Django 4.0.5 on 2022-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0005_rename_athlete_id_event_event_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_key',
            field=models.IntegerField(),
        ),
    ]
